### PR TITLE
Setup leaderboard

### PR DESCRIPTION
**Pull request by Rana-Mudassir**
- Created the HTML file with plain HTML markup.
- Used ES6 modules to feed data dynamically once the page loads.
- Styled to suit the given wireframe.
- Fix linter errors
- Utilized Gitflow

### CODE REVIEW

**Comment by Rana-Mudassir** [comment]
I have been facing this webhint error since I started working on this project, I have tried my very best to solve this but have been unsuccessful so far. I am attaching a screenshot of the error in the terminal. I am submitting this PR with the hopes that you as a reviewer might be able to help me with this.
Regards, 
dist

**Comment by algerina** [comment]
Hi @Rana-Mudassir, 
I guess that the issue is in your Linters config, try replacing your file linters.yml with the following file [linters.yml](https://github.com/microverseinc/linters-config/blob/master/javascript/.github/workflows/linters.yml) please.

**Comment by Rana-Mudassir** [comment]
I updated, Please check

**Review by Tufahel — APPROVED** [review]
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

Hi @Rana-Mudassir  :wave: 
 
Your project is complete now!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 👏🏻



:heavy_check_mark: Readme is professional.
:heavy_check_mark: Descriptive pull request.
:heavy_check_mark: Meaningful commit message.
:heavy_check_mark: Follow gitflow

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
